project:
  type: website
  output-dir: docs
  # pre-render:
  #   - scripts/pre_canonicalise_tags.py
resources:
  - CNAME

website:
  site-url: "https://alexleeds.com"
  title: "Alex Leeds"
  description: "Alex Leeds is a data scientist living in NYC"
  favicon: img/letter_a_by_md_tanvirul_haque.jpg
  navbar:
    logo: img/house-solid.svg
    right:
      - href: writing
        text: WRITING
      - href: projects
        text: PROJECTS
      - href: https://about.hellosleuth.com/
        text: SLEUTH
  page-footer:
    left: 'Made with <a href="https://quarto.org/">Quarto</a>'
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>
        {
          "@context":"http://www.schema.org",
          "@type":"Person",
          "name":"Alex Leeds",
          "jobTitle":"Data scientist",
          "height":"72 inches",
          "gender":"male",
          "description":"Alex Leeds is a data scientist living in NYC.",
          "url":"https://alexleeds.com",
          "address":{
            "@type":"PostalAddress",
            "addressLocality":"New York",
            "addressRegion":"NY",
            "postalCode":"10021",
            "addressCountry":"United States"
          },
          "birthDate":"1980-06-29",
          "birthPlace":"New York, NY"
        }
        </script>
        <script>
          document.addEventListener('DOMContentLoaded', function () {
            const links = document.querySelectorAll('a[href^="http"]');
            links.forEach(link => {
              if (!link.href.includes(location.hostname)) {
                link.target = '_blank';
                // Optional: Add rel="noopener noreferrer" for security reasons
                link.rel = 'noopener noreferrer';
              }
            });
          });
        </script>