project:
  type: website
  output-dir: docs
  # pre-render:
  #   - scripts/pre_canonicalise_tags.py
resources:
  - CNAME

website:
  site-url: "https://alexleeds.com"
  title: "Alex Leeds"
  description: "Alex Leeds is a data scientist living in NYC"
  favicon: img/letter_a_by_md_tanvirul_haque.jpg
  navbar:
    logo: img/house-solid.svg
    right:
      - href: writing
        text: WRITING
      - href: reading
        text: READING
      - href: projects
        text: PROJECTS
      - href: https://hellosleuth.com/
        text: SLEUTH
  page-footer:
    left: 'Made with <a href="https://quarto.org/">Quarto</a>'
  twitter-card: true
  open-graph: true
  google-analytics: 'G-55MDQLPS7F'

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header: header.html
